config/routes.rb
Rails.application.routes.draw do
  resources :quiz, only: [:index] do
    post :evaluate_test, on: :collection
    get :show_score, on: :collection
  end

  root 'quiz#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  before_action :set_questions, only: [:index, :run_test, :evaluate_test, :show_score]

  def index
  end

  def run_test
    @score = 0
  end

  def evaluate_test
    @score = 0

    params[:answers].each do |question_id, answer|
      question = @questions.find(question_id.to_i)
      @score += 1 if answer == question.answer
    end

    session[:quiz_score] = @score
    redirect_to show_score_quiz_index_path
  end

  def show_score
    @score = session[:quiz_score] || 0
  end

  private

  def set_questions
    @questions = Question.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quiz/index.html.erb
<h1>Quiz</h1>

<%= form_tag(evaluate_test_quiz_index_path, method: :post) do %>
  <% @questions.each do |question| %>
    <p><%= question.prompt %></p>
    <%= radio_button_tag "answers[#{question.id}]", 'a' %> (a)
    <%= radio_button_tag "answers[#{question.id}]", 'b' %> (b)
    <%= radio_button_tag "answers[#{question.id}]", 'c' %> (c)
  <% end %>

  <%= submit_tag "Submit" %>
<% end %>

app/views/quiz/show_score.html.erb
<h1>Your Quiz Score</h1>

<p>You scored <%= @score %> out of <%= @questions.count %>.</p>

<%= link_to 'Try Again', quiz_index_path %>